version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    volumes:
      - fmc-etcd:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name
      - "fmc-etcd0"
      - --data-dir
      - /etcd-data
      - --initial-cluster-state
      - new
    ports:
      - "2379:2379"
      - "2380:2380"
volumes:
  fmc-etcd:
