(ns aux.kubernetes.kubernetes-data
  (:require [clojure.test :refer :all]))

(def nodes
  [{:metadata {:name "ip-10-129-210-13.ec2.internal"},
    :status {:addresses [{:type "InternalIP", :address "10.129.210.13"}
                         {:type "InternalDNS", :address "ip-10-129-210-13.ec2.internal"}
                         {:type "Hostname", :address "ip-10-129-210-13.ec2.internal"}]}}
   {:metadata {:name "ip-10-129-210-64.ec2.internal"},
    :status {:addresses [{:type "InternalIP", :address "10.129.210.64"}
                         {:type "InternalDNS", :address "ip-10-129-210-64.ec2.internal"}
                         {:type "Hostname", :address "ip-10-129-210-64.ec2.internal"}]}}
   {:metadata {:name "ip-10-129-218-235.ec2.internal"},
    :status {:addresses [{:type "InternalIP", :address "10.129.218.235"}
                         {:type "InternalDNS", :address "ip-10-129-218-235.ec2.internal"}
                         {:type "Hostname", :address "ip-10-129-218-235.ec2.internal"}]}}])


(def pods
  [{:metadata {:name            "auth-667684b76b-z7qzs",
               :labels          {:formicarium.io/application "auth", :pod-template-hash "2232406326"},
               :annotations     #:iam.amazonaws.com{:role "arn:aws:iam::552767473918:role/test/fmc-service/a/test-a-fmc-service-role"},
               :namespace       "carlos"},
    :spec     {:containers                    [{:terminationMessagePolicy "File",
                                                :volumeMounts             [{:name "shared-m2", :mountPath "/root/.m2"}
                                                                           {:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :name                     "auth",
                                                :env                      [{:name  "NU_ENV_CONFIG",
                                                                            :value "{\"dynamodb\":{\"endpoint\":\"http://dynamodb:8000\",\"table\":\"auth\"},\"primary_brokers\":\"kafka:9092\",\"zk_primary\":\"zookeeper\",\"fraudster_account_recovery_redis_host\":\"redis\",\"prototype\":\"s0\",\"services\":{\"slack-client\":\"http://slack-client:8080\",\"morpheus\":\"http://morpheus:8080\",\"tapir\":\"http://tapir:8080\",\"nl-watchtower\":\"http://nl-watchtower:8080\",\"geller\":\"http://geller:8080\",\"the-smith\":\"http://the-smith:8080\",\"crm-client\":\"http://crm-client:8080\",\"magnitude\":\"http://magnitude:8080\",\"asheara\":\"http://asheara:8080\",\"hal\":\"http://hal:8080\",\"chatinho\":\"http://chatinho:8080\",\"onboarding\":\"http://onboarding:8080\",\"pidgey\":\"http://pidgey:8080\",\"webapp-proxy\":\"http://webapp-proxy:8080\",\"tank\":\"http://tank:8080\",\"newman\":\"http://newman:8080\",\"charging\":\"http://charging:8080\",\"papers-please\":\"http://papers-please:8080\",\"banner\":\"http://banner:8080\",\"jd-npc-bi-client\":\"http://jd-npc-bi-client:8080\",\"zuniga\":\"http://zuniga:8080\",\"fredo\":\"http://fredo:8080\",\"customers\":\"http://customers:8080\",\"surrender\":\"http://surrender:8080\",\"zakarum\":\"http://zakarum:8080\",\"forex\":\"http://forex:8080\",\"image-processor\":\"http://image-processor:8080\",\"abbc-client\":\"http://abbc-client:8080\",\"bureau\":\"http://bureau:8080\",\"stormshield\":\"http://stormshield:8080\",\"liza\":\"http://liza:8080\",\"teller\":\"http://teller:8080\",\"teleport-auth\":\"http://teleport-auth:8080\",\"treasury\":\"http://treasury:8080\",\"conrado\":\"http://conrado:8080\",\"control-tower\":\"http://control-tower:8080\",\"gallywix\":\"http://gallywix:8080\",\"balboa\":\"http://balboa:8080\",\"charlotte\":\"http://charlotte:8080\",\"toasty\":\"http://toasty:8080\",\"chat-roulette-service\":\"http://chat-roulette-service:8080\",\"mutual-tls-test\":\"http://mutual-tls-test:8080\",\"wendy\":\"http://wendy:8080\",\"acquisition\":\"http://acquisition:8080\",\"boletonator\":\"http://boletonator:8080\",\"backoffice\":\"https://staging-backoffice.nubank.com.br\",\"sendman\":\"http://sendman:8080\",\"bleach\":\"http://bleach:8080\",\"gradle-cache\":\"http://gradle-cache:8080\",\"line-items\":\"http://line-items:8080\",\"counterspell\":\"http://counterspell:8080\",\"hal-v3\":\"http://hal-v3:8080\",\"jd-npc-client\":\"http://jd-npc-client:8080\",\"mordor\":\"http://mordor:8080\",\"roosevelt-proxy\":\"http://roosevelt-proxy:8080\",\"delivery\":\"http://delivery:8080\",\"bonafont\":\"http://bonafont:8080\",\"boleto-authorizer\":\"http://boleto-authorizer:8080\",\"bilbo\":\"http://bilbo:8080\",\"financeira-credit-ledger\":\"http://financeira-credit-ledger:8080\",\"peter-pan\":\"http://peter-pan:8080\",\"warehouse\":\"http://warehouse:8080\",\"abu\":\"http://abu:8080\",\"parrot\":\"http://parrot:8080\",\"stormguild\":\"http://stormguild:8080\",\"skyler\":\"http://skyler:8080\",\"wololo\":\"http://wololo:8080\",\"dinowrangler\":\"http://dinowrangler:8080\",\"auth\":\"http://auth:8080\",\"mercurio\":\"http://mercurio:8080\",\"uppercut\":\"http://uppercut:8080\",\"vulcano\":\"http://vulcano:8080\",\"billing\":\"http://billing:8080\",\"aprenda-hiring\":\"http://aprenda-hiring:8080\",\"smee\":\"http://smee:8080\",\"inductor\":\"http://inductor:8080\",\"curva-de-rio\":\"http://curva-de-rio:8080\",\"acessodigital-client\":\"http://acessodigital-client:8080\",\"warriv\":\"http://warriv:8080\",\"lost-boy\":\"http://lost-boy:8080\",\"giba\":\"http://giba:8080\",\"atenta\":\"http://atenta:8080\",\"lusa\":\"http://lusa:8080\",\"horadric\":\"http://horadric:8080\",\"charlotte-v4\":\"http://charlotte-v4:8080\",\"shore\":\"http://shore:8080\",\"burrow\":\"http://burrow:8080\",\"lovelace\":\"http://lovelace:8080\",\"aprenda\":\"http://aprenda:8080\",\"russ\":\"http://russ:8080\",\"mica\":\"http://mica:8080\",\"riverbend\":\"http://riverbend:8080\",\"portal-gun\":\"http://portal-gun:8080\",\"geo\":\"http://geo:8080\",\"griswold\":\"http://griswold:8080\",\"barragem\":\"http://barragem:8080\",\"sr-barriga\":\"http://sr-barriga:8080\",\"mortician\":\"http://mortician:8080\",\"buguinho\":\"http://buguinho:8080\",\"maitre\":\"http://maitre:8080\",\"tyrael\":\"http://tyrael:8080\",\"arnaldo\":\"http://arnaldo:8080\",\"life-tap\":\"http://life-tap:8080\",\"double-entry-consumers\":\"http://double-entry-consumers:8080\",\"kanai\":\"http://kanai:8080\",\"crebito\":\"http://crebito:8080\",\"consigliere\":\"http://consigliere:8080\",\"sommelier\":\"http://sommelier:8080\",\"buck-cache\":\"http://buck-cache:8080\",\"customs\":\"http://customs:8080\",\"russ-model-v2\":\"http://russ-model-v2:8080\",\"stargate\":\"http://stargate:8080\",\"paperboy\":\"http://paperboy:8080\",\"marte\":\"http://marte:8080\",\"chateau\":\"http://chateau:8080\",\"newman-model\":\"http://newman-model:8080\",\"facade\":\"http://facade:8080\",\"newman-model-v1\":\"http://newman-model-v1:8080\",\"jd-pcps-client\":\"http://jd-pcps-client:8080\",\"bifrost\":\"http://bifrost:8080\",\"auriel\":\"http://auriel:8080\",\"rewards-ledger\":\"http://rewards-ledger:8080\",\"tx-ranger\":\"http://tx-ranger:8080\",\"lusa-v5\":\"http://lusa-v5:8080\",\"needful-things\":\"http://needful-things:8080\",\"kaelan\":\"http://kaelan:8080\",\"tempo\":\"http://tempo:8080\",\"jurassic-park\":\"http://jurassic-park:8080\",\"nana\":\"http://nana:8080\",\"nudata-client\":\"http://nudata-client:8080\",\"savings-accounts\":\"http://savings-accounts:8080\",\"piv\":\"http://piv:8080\",\"web-app\":\"https://staging-conta.nubank.com.br\",\"mermaid\":\"http://mermaid:8080\",\"mobile-hiring-test\":\"http://mobile-hiring-test:8080\",\"big-mama\":\"http://big-mama:8080\",\"pidgeotto\":\"http://pidgeotto:8080\",\"barney\":\"http://barney:8080\",\"waypoint\":\"http://waypoint:8080\",\"model-server\":\"http://model-server:8080\",\"lusa-v4\":\"http://lusa-v4:8080\",\"tyrion\":\"http://tyrion:8080\",\"grace\":\"http://grace:8080\",\"blackleach\":\"http://blackleach:8080\",\"zendesk_uri\":\"https://nubank1410870593.zendesk.com/api/v2/\",\"triage\":\"http://triage:8080\",\"sharingan\":\"http://sharingan:8080\",\"beggar\":\"http://beggar:8080\",\"double-entry\":\"http://double-entry:8080\",\"gabyves\":\"http://gabyves:8080\",\"pandora\":\"http://pandora:8080\",\"nvtf\":\"http://nvtf:8080\",\"ronaldo\":\"http://ronaldo:8080\",\"glados\":\"http://glados:8080\",\"brasi\":\"http://brasi:8080\",\"pokedex\":\"http://pokedex:8080\",\"nephalem\":\"http://nephalem:8080\",\"mkt-website\":\"https://staging-nubank.com.br\",\"pagueveloz-client\":\"http://pagueveloz-client:8080\",\"vitrine\":\"http://vitrine:8080\",\"cruise-control\":\"http://cruise-control:8080\",\"corleone\":\"http://corleone:8080\",\"norton\":\"http://norton:8080\",\"netuno\":\"http://netuno:8080\",\"theodore\":\"http://theodore:8080\",\"correnteza\":\"http://correnteza:8080\",\"financeira-reporter\":\"http://financeira-reporter:8080\",\"abomination\":\"http://abomination:8080\",\"insulator\":\"http://insulator:8080\",\"babel\":\"http://babel:8080\",\"social\":\"http://social:8080\",\"backoffice-proxy\":\"http://backoffice-proxy:8080\",\"ackinator\":\"http://ackinator:8080\",\"lydia\":\"http://lydia:8080\",\"stevie\":\"http://stevie:8080\",\"deckard\":\"http://deckard:8080\",\"cepage\":\"http://cepage:8080\",\"teleport-proxy\":\"http://teleport-proxy:8080\",\"metabase\":\"http://metabase:8080\",\"feed\":\"http://feed:8080\",\"severino\":\"http://severino:8080\",\"karma-police\":\"http://karma-police:8080\",\"notification\":\"http://notification:8080\",\"diablo\":\"http://diablo:8080\",\"email-client\":\"http://email-client:8080\",\"jd-spb-client\":\"http://jd-spb-client:8080\",\"chat-client\":\"http://chat-client:8080\",\"soviet-kraken\":\"http://soviet-kraken:8080\",\"neymar\":\"http://neymar:8080\",\"rubao\":\"http://rubao:8080\",\"hal-v2\":\"http://hal-v2:8080\",\"maat\":\"http://maat:8080\",\"mancini\":\"http://mancini:8080\",\"russ-model\":\"http://russ-model:8080\",\"negociant\":\"http://negociant:8080\",\"hal-v1\":\"http://hal-v1:8080\",\"webhook\":\"http://webhook:8080\",\"spaceteam\":\"http://spaceteam:8080\",\"gemalto-client\":\"http://gemalto-client:8080\",\"rtm-proxy\":\"http://rtm-proxy:8080\",\"aloka\":\"http://aloka:8080\",\"messaggero\":\"http://messaggero:8080\",\"chat-roulette\":\"http://chat-roulette:8080\",\"proximo\":\"http://proximo:8080\",\"financing\":\"http://financing:8080\",\"hook\":\"http://hook:8080\",\"chargebacks\":\"http://chargebacks:8080\",\"metapod\":\"http://metapod:8080\",\"abrams\":\"http://abrams:8080\",\"purgatory\":\"http://purgatory:8080\",\"nexxera-client\":\"http://nexxera-client:8080\",\"meeseeks\":\"http://meeseeks:8080\",\"censo\":\"http://censo:8080\",\"mipsim\":\"http://mipsim:8080\",\"zedruu\":\"http://zedruu:8080\",\"analytics\":\"http://analytics:8080\",\"idtrust-client\":\"http://idtrust-client:8080\",\"hagen\":\"http://hagen:8080\",\"credit-card-accounts\":\"http://credit-card-accounts:8080\",\"ledger\":\"http://ledger:8080\",\"plutao\":\"http://plutao:8080\",\"scatterbrain\":\"http://scatterbrain:8080\"},\"token-revoked\":{\"endpoint\":\"http://dynamodb:8000\",\"table\":\"token-revoked\"},\"certificates\":{\"endpoint\":\"http://dynamodb:8000\",\"table\":\"auth-certificates\"},\"datomic_uri\":\"datomic:dev://transactor:4334/auth\",\"account_recovery_redis_host\":\"redis\",\"crl\":{\"endpoint\":\"http://dynamodb:8000\",\"table\":\"certificate-revocation-list\"},\"proof_redis_host\":\"redis\",\"environment\":\"local\",\"all-tokens-revoked\":{\"endpoint\":\"http://dynamodb:8000\",\"table\":\"all-tokens-revoked\"},\"shards\":{\"s0\":{\"zk_primary\":\"zookeeper\"}},\"ratelimit_redis_host\":\"redis\",\"dev_port\":8080,\"login_webapp_store_redis_host\":\"redis\",\"code_2fa_redis_host\":\"redis\"}"}
                                                                           {:name "LEIN_REPL_PORT", :value "34000"}
                                                                           {:name "LEIN_REPL_HOST", :value "0.0.0.0"}
                                                                           {:name "STARTUP_CLONE", :value "true"}
                                                                           {:name "START_AFTER_PULL", :value "false"}
                                                                           {:name "STINGER_PORT", :value "24000"}
                                                                           {:name "APP_PATH", :value "/app"}
                                                                           {:name "STINGER_SCRIPTS", :value "/scripts"}
                                                                           {:name "GIT_URI", :value "http://tanajura:6666/auth.git"}],
                                                :ports                    [{:name "stinger", :containerPort 24000, :protocol "TCP"}
                                                                           {:name "default", :containerPort 8080, :protocol "TCP"}
                                                                           {:name "run-dev-repl", :containerPort 34000, :protocol "TCP"}
                                                                           {:name "common-repl", :containerPort 35000, :protocol "TCP"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :imagePullPolicy          "IfNotPresent",
                                                :image                    "formicarium/chamber-lein:0.0.13",
                                                :resources                {}}],
               :hostname                      "auth",
               :volumes                       [{:name "shared-m2", :hostPath {:path "/var/.m2", :type "DirectoryOrCreate"}}
                                               {:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :nodeName                      "ip-10-129-218-235.ec2.internal",
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:name              "dynamodb-96df8df6c-kfp7n",
               :labels            {:formicarium.io/application "dynamodb", :pod-template-hash "528948927"},
               :namespace         "carlos"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "dynamodb",
               :containers                    [{:name                     "dynamodb",
                                                :image                    "quay.io/nubank/nudev-dynamodb",
                                                :ports                    [{:name "client", :containerPort 8000, :protocol "TCP"}],
                                                :resources                {},
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :terminationMessagePolicy "File",
                                                :imagePullPolicy          "Always"}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-218-235.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "hive", :pod-template-hash "2857630519"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "hive-6d9cb7495f",
                                    :uid                "ec1b5c03-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec1e0655-1830-11e9-a919-06375bf528b4",
               :name              "hive-6d9cb7495f-pvgjv",
               :resourceVersion   "16195908",
               :selfLink          "/api/v1/namespaces/carlos/pods/hive-6d9cb7495f-pvgjv",
               :namespace         "carlos",
               :generateName      "hive-6d9cb7495f-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "hive",
               :containers                    [{:name                     "hive",
                                                :image                    "formicarium/hive:5d98c11ea5db32bd8db5478e7389f0ac668d79b3",
                                                :ports                    [{:name "default", :containerPort 8080, :protocol "TCP"}
                                                                           {:name "repl", :containerPort 2222, :protocol "TCP"}
                                                                           {:name "zmq", :containerPort 9898, :protocol "TCP"}],
                                                :resources                {},
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :terminationMessagePolicy "File",
                                                :imagePullPolicy          "IfNotPresent"}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-218-235.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "kafka", :pod-template-hash "1287163291"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "kafka-56dc5b76f5",
                                    :uid                "ec4a68f7-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec4b062f-1830-11e9-a919-06375bf528b4",
               :name              "kafka-56dc5b76f5-c822c",
               :resourceVersion   "16195949",
               :selfLink          "/api/v1/namespaces/carlos/pods/kafka-56dc5b76f5-c822c",
               :namespace         "carlos",
               :generateName      "kafka-56dc5b76f5-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "kafka",
               :containers                    [{:terminationMessagePolicy "File",
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :name                     "kafka",
                                                :env                      [{:name "ZK_HOST", :value "zookeeper"}],
                                                :ports                    [{:name "client", :containerPort 9092, :protocol "TCP"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :imagePullPolicy          "Always",
                                                :image                    "quay.io/nubank/nudev-kafka",
                                                :resources                {}}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-210-13.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "maat", :pod-template-hash "2439337092"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "maat-687f77c4f6",
                                    :uid                "0ba607f9-19c9-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-16T19:58:08Z",
               :uid               "0ba9c54b-19c9-11e9-a919-06375bf528b4",
               :name              "maat-687f77c4f6-m2h52",
               :resourceVersion   "16570147",
               :selfLink          "/api/v1/namespaces/carlos/pods/maat-687f77c4f6-m2h52",
               :annotations       #:iam.amazonaws.com{:role "arn:aws:iam::552767473918:role/test/fmc-service/a/test-a-fmc-service-role"},
               :namespace         "carlos",
               :generateName      "maat-687f77c4f6-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "maat",
               :containers                    [{:terminationMessagePolicy "File",
                                                :volumeMounts             [{:name "shared-m2", :mountPath "/root/.m2"}
                                                                           {:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :name                     "maat",
                                                :env                      [{:name  "NU_ENV_CONFIG",
                                                                            :value "{\"environment\":\"local\",\"dev_port\":8080,\"zk_primary\":\"zookeeper\",\"primary_brokers\":\"kafka:9092\",\"prototype\":\"s0\",\"services\":{\"slack-client\":\"http://slack-client:8080\",\"morpheus\":\"http://morpheus:8080\",\"tapir\":\"http://tapir:8080\",\"nl-watchtower\":\"http://nl-watchtower:8080\",\"geller\":\"http://geller:8080\",\"the-smith\":\"http://the-smith:8080\",\"crm-client\":\"http://crm-client:8080\",\"magnitude\":\"http://magnitude:8080\",\"asheara\":\"http://asheara:8080\",\"hal\":\"http://hal:8080\",\"chatinho\":\"http://chatinho:8080\",\"onboarding\":\"http://onboarding:8080\",\"pidgey\":\"http://pidgey:8080\",\"webapp-proxy\":\"http://webapp-proxy:8080\",\"tank\":\"http://tank:8080\",\"newman\":\"http://newman:8080\",\"charging\":\"http://charging:8080\",\"papers-please\":\"http://papers-please:8080\",\"banner\":\"http://banner:8080\",\"jd-npc-bi-client\":\"http://jd-npc-bi-client:8080\",\"zuniga\":\"http://zuniga:8080\",\"fredo\":\"http://fredo:8080\",\"customers\":\"http://customers:8080\",\"surrender\":\"http://surrender:8080\",\"zakarum\":\"http://zakarum:8080\",\"forex\":\"http://forex:8080\",\"image-processor\":\"http://image-processor:8080\",\"abbc-client\":\"http://abbc-client:8080\",\"bureau\":\"http://bureau:8080\",\"stormshield\":\"http://stormshield:8080\",\"liza\":\"http://liza:8080\",\"teller\":\"http://teller:8080\",\"teleport-auth\":\"http://teleport-auth:8080\",\"treasury\":\"http://treasury:8080\",\"conrado\":\"http://conrado:8080\",\"control-tower\":\"http://control-tower:8080\",\"gallywix\":\"http://gallywix:8080\",\"balboa\":\"http://balboa:8080\",\"charlotte\":\"http://charlotte:8080\",\"toasty\":\"http://toasty:8080\",\"chat-roulette-service\":\"http://chat-roulette-service:8080\",\"mutual-tls-test\":\"http://mutual-tls-test:8080\",\"wendy\":\"http://wendy:8080\",\"acquisition\":\"http://acquisition:8080\",\"boletonator\":\"http://boletonator:8080\",\"cutia\":\"http://cutia:8080\",\"backoffice\":\"https://staging-backoffice.nubank.com.br\",\"sendman\":\"http://sendman:8080\",\"bleach\":\"http://bleach:8080\",\"gradle-cache\":\"http://gradle-cache:8080\",\"line-items\":\"http://line-items:8080\",\"counterspell\":\"http://counterspell:8080\",\"hal-v3\":\"http://hal-v3:8080\",\"jd-npc-client\":\"http://jd-npc-client:8080\",\"mordor\":\"http://mordor:8080\",\"roosevelt-proxy\":\"http://roosevelt-proxy:8080\",\"delivery\":\"http://delivery:8080\",\"bonafont\":\"http://bonafont:8080\",\"boleto-authorizer\":\"http://boleto-authorizer:8080\",\"bilbo\":\"http://bilbo:8080\",\"financeira-credit-ledger\":\"http://financeira-credit-ledger:8080\",\"peter-pan\":\"http://peter-pan:8080\",\"warehouse\":\"http://warehouse:8080\",\"abu\":\"http://abu:8080\",\"rdbrasi\":\"http://rdbrasi:8080\",\"parrot\":\"http://parrot:8080\",\"stormguild\":\"http://stormguild:8080\",\"skyler\":\"http://skyler:8080\",\"wololo\":\"http://wololo:8080\",\"dinowrangler\":\"http://dinowrangler:8080\",\"auth\":\"http://auth:8080\",\"mercurio\":\"http://mercurio:8080\",\"uppercut\":\"http://uppercut:8080\",\"vulcano\":\"http://vulcano:8080\",\"billing\":\"http://billing:8080\",\"aprenda-hiring\":\"http://aprenda-hiring:8080\",\"smee\":\"http://smee:8080\",\"inductor\":\"http://inductor:8080\",\"curva-de-rio\":\"http://curva-de-rio:8080\",\"acessodigital-client\":\"http://acessodigital-client:8080\",\"warriv\":\"http://warriv:8080\",\"lost-boy\":\"http://lost-boy:8080\",\"giba\":\"http://giba:8080\",\"atenta\":\"http://atenta:8080\",\"lusa\":\"http://lusa:8080\",\"horadric\":\"http://horadric:8080\",\"charlotte-v4\":\"http://charlotte-v4:8080\",\"shore\":\"http://shore:8080\",\"burrow\":\"http://burrow:8080\",\"lovelace\":\"http://lovelace:8080\",\"aprenda\":\"http://aprenda:8080\",\"russ\":\"http://russ:8080\",\"mica\":\"http://mica:8080\",\"riverbend\":\"http://riverbend:8080\",\"portal-gun\":\"http://portal-gun:8080\",\"geo\":\"http://geo:8080\",\"griswold\":\"http://griswold:8080\",\"barragem\":\"http://barragem:8080\",\"sr-barriga\":\"http://sr-barriga:8080\",\"mortician\":\"http://mortician:8080\",\"buguinho\":\"http://buguinho:8080\",\"maitre\":\"http://maitre:8080\",\"tyrael\":\"http://tyrael:8080\",\"arnaldo\":\"http://arnaldo:8080\",\"life-tap\":\"http://life-tap:8080\",\"double-entry-consumers\":\"http://double-entry-consumers:8080\",\"kanai\":\"http://kanai:8080\",\"crebito\":\"http://crebito:8080\",\"consigliere\":\"http://consigliere:8080\",\"sommelier\":\"http://sommelier:8080\",\"buck-cache\":\"http://buck-cache:8080\",\"customs\":\"http://customs:8080\",\"russ-model-v2\":\"http://russ-model-v2:8080\",\"stargate\":\"http://stargate:8080\",\"paperboy\":\"http://paperboy:8080\",\"marte\":\"http://marte:8080\",\"chateau\":\"http://chateau:8080\",\"newman-model\":\"http://newman-model:8080\",\"facade\":\"http://facade:8080\",\"newman-model-v1\":\"http://newman-model-v1:8080\",\"jd-pcps-client\":\"http://jd-pcps-client:8080\",\"bifrost\":\"http://bifrost:8080\",\"auriel\":\"http://auriel:8080\",\"rewards-ledger\":\"http://rewards-ledger:8080\",\"tx-ranger\":\"http://tx-ranger:8080\",\"lusa-v5\":\"http://lusa-v5:8080\",\"needful-things\":\"http://needful-things:8080\",\"kaelan\":\"http://kaelan:8080\",\"tempo\":\"http://tempo:8080\",\"jurassic-park\":\"http://jurassic-park:8080\",\"nana\":\"http://nana:8080\",\"grafana\":\"http://grafana:8080\",\"nudata-client\":\"http://nudata-client:8080\",\"savings-accounts\":\"http://savings-accounts:8080\",\"piv\":\"http://piv:8080\",\"web-app\":\"https://staging-conta.nubank.com.br\",\"mermaid\":\"http://mermaid:8080\",\"mobile-hiring-test\":\"http://mobile-hiring-test:8080\",\"big-mama\":\"http://big-mama:8080\",\"pidgeotto\":\"http://pidgeotto:8080\",\"barney\":\"http://barney:8080\",\"waypoint\":\"http://waypoint:8080\",\"model-server\":\"http://model-server:8080\",\"lusa-v4\":\"http://lusa-v4:8080\",\"tyrion\":\"http://tyrion:8080\",\"grace\":\"http://grace:8080\",\"blackleach\":\"http://blackleach:8080\",\"zendesk_uri\":\"https://nubank1410870593.zendesk.com/api/v2/\",\"triage\":\"http://triage:8080\",\"sharingan\":\"http://sharingan:8080\",\"beggar\":\"http://beggar:8080\",\"double-entry\":\"http://double-entry:8080\",\"gabyves\":\"http://gabyves:8080\",\"pandora\":\"http://pandora:8080\",\"nvtf\":\"http://nvtf:8080\",\"ronaldo\":\"http://ronaldo:8080\",\"glados\":\"http://glados:8080\",\"brasi\":\"http://brasi:8080\",\"pokedex\":\"http://pokedex:8080\",\"nephalem\":\"http://nephalem:8080\",\"mkt-website\":\"https://staging-nubank.com.br\",\"pagueveloz-client\":\"http://pagueveloz-client:8080\",\"vitrine\":\"http://vitrine:8080\",\"cruise-control\":\"http://cruise-control:8080\",\"corleone\":\"http://corleone:8080\",\"norton\":\"http://norton:8080\",\"netuno\":\"http://netuno:8080\",\"theodore\":\"http://theodore:8080\",\"correnteza\":\"http://correnteza:8080\",\"financeira-reporter\":\"http://financeira-reporter:8080\",\"abomination\":\"http://abomination:8080\",\"insulator\":\"http://insulator:8080\",\"babel\":\"http://babel:8080\",\"social\":\"http://social:8080\",\"backoffice-proxy\":\"http://backoffice-proxy:8080\",\"ackinator\":\"http://ackinator:8080\",\"lydia\":\"http://lydia:8080\",\"stevie\":\"http://stevie:8080\",\"deckard\":\"http://deckard:8080\",\"cepage\":\"http://cepage:8080\",\"teleport-proxy\":\"http://teleport-proxy:8080\",\"metabase\":\"http://metabase:8080\",\"feed\":\"http://feed:8080\",\"severino\":\"http://severino:8080\",\"karma-police\":\"http://karma-police:8080\",\"notification\":\"http://notification:8080\",\"diablo\":\"http://diablo:8080\",\"email-client\":\"http://email-client:8080\",\"jd-spb-client\":\"http://jd-spb-client:8080\",\"chat-client\":\"http://chat-client:8080\",\"soviet-kraken\":\"http://soviet-kraken:8080\",\"neymar\":\"http://neymar:8080\",\"rubao\":\"http://rubao:8080\",\"hal-v2\":\"http://hal-v2:8080\",\"maat\":\"http://maat:8080\",\"mancini\":\"http://mancini:8080\",\"russ-model\":\"http://russ-model:8080\",\"negociant\":\"http://negociant:8080\",\"hal-v1\":\"http://hal-v1:8080\",\"webhook\":\"http://webhook:8080\",\"spaceteam\":\"http://spaceteam:8080\",\"gemalto-client\":\"http://gemalto-client:8080\",\"rtm-proxy\":\"http://rtm-proxy:8080\",\"aloka\":\"http://aloka:8080\",\"messaggero\":\"http://messaggero:8080\",\"chat-roulette\":\"http://chat-roulette:8080\",\"proximo\":\"http://proximo:8080\",\"financing\":\"http://financing:8080\",\"hook\":\"http://hook:8080\",\"chargebacks\":\"http://chargebacks:8080\",\"metapod\":\"http://metapod:8080\",\"abrams\":\"http://abrams:8080\",\"purgatory\":\"http://purgatory:8080\",\"nexxera-client\":\"http://nexxera-client:8080\",\"meeseeks\":\"http://meeseeks:8080\",\"censo\":\"http://censo:8080\",\"mipsim\":\"http://mipsim:8080\",\"zedruu\":\"http://zedruu:8080\",\"analytics\":\"http://analytics:8080\",\"idtrust-client\":\"http://idtrust-client:8080\",\"hagen\":\"http://hagen:8080\",\"credit-card-accounts\":\"http://credit-card-accounts:8080\",\"ledger\":\"http://ledger:8080\",\"plutao\":\"http://plutao:8080\",\"scatterbrain\":\"http://scatterbrain:8080\"}}"}
                                                                           {:name "LEIN_REPL_PORT", :value "34000"}
                                                                           {:name "LEIN_REPL_HOST", :value "0.0.0.0"}
                                                                           {:name "STARTUP_CLONE", :value "true"}
                                                                           {:name "START_AFTER_PULL", :value "false"}
                                                                           {:name "STINGER_PORT", :value "24000"}
                                                                           {:name "APP_PATH", :value "/app"}
                                                                           {:name "STINGER_SCRIPTS", :value "/scripts"}
                                                                           {:name "GIT_URI", :value "http://tanajura:6666/maat.git"}],
                                                :ports                    [{:name "stinger", :containerPort 24000, :protocol "TCP"}
                                                                           {:name "default", :containerPort 8080, :protocol "TCP"}
                                                                           {:name "run-dev-repl", :containerPort 34000, :protocol "TCP"}
                                                                           {:name "common-repl", :containerPort 35000, :protocol "TCP"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :imagePullPolicy          "IfNotPresent",
                                                :image                    "formicarium/chamber-lein:0.0.13",
                                                :resources                {}}],
               :volumes                       [{:name "shared-m2", :hostPath {:path "/var/.m2", :type "DirectoryOrCreate"}}
                                               {:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-210-13.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "redis", :pod-template-hash "517669340"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "redis-95cbbf784",
                                    :uid                "ec6ef774-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec6f7ca1-1830-11e9-a919-06375bf528b4",
               :name              "redis-95cbbf784-hbvsn",
               :resourceVersion   "16195945",
               :selfLink          "/api/v1/namespaces/carlos/pods/redis-95cbbf784-hbvsn",
               :namespace         "carlos",
               :generateName      "redis-95cbbf784-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "redis",
               :containers                    [{:name                     "redis",
                                                :image                    "redis",
                                                :ports                    [{:name "client", :containerPort 6379, :protocol "TCP"}],
                                                :resources                {},
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :terminationMessagePolicy "File",
                                                :imagePullPolicy          "Always"}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-218-235.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "tanajura", :pod-template-hash "2800663179"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "tanajura-6d44bb75cf",
                                    :uid                "ec270209-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec27994f-1830-11e9-a919-06375bf528b4",
               :name              "tanajura-6d44bb75cf-t446b",
               :resourceVersion   "16195924",
               :selfLink          "/api/v1/namespaces/carlos/pods/tanajura-6d44bb75cf-t446b",
               :namespace         "carlos",
               :generateName      "tanajura-6d44bb75cf-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "tanajura",
               :containers                    [{:terminationMessagePolicy "File",
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :name                     "tanajura",
                                                :env                      [{:name "DEVSPACE", :value "carlos"}
                                                                           {:name "SOIL_URL", :value "http://soil.test-fmc-a.nubank.com.br"}],
                                                :ports                    [{:name "default", :containerPort 3002, :protocol "TCP"}
                                                                           {:name "git", :containerPort 6666, :protocol "TCP"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :imagePullPolicy          "IfNotPresent",
                                                :image                    "formicarium/tanajura:1.8.1",
                                                :resources                {}}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-210-13.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "transactor", :pod-template-hash "1815925979"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "transactor-5d59f69fcf",
                                    :uid                "ec551823-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec55ac94-1830-11e9-a919-06375bf528b4",
               :name              "transactor-5d59f69fcf-7d9s2",
               :resourceVersion   "16195937",
               :selfLink          "/api/v1/namespaces/carlos/pods/transactor-5d59f69fcf-7d9s2",
               :namespace         "carlos",
               :generateName      "transactor-5d59f69fcf-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "transactor",
               :containers                    [{:terminationMessagePolicy "File",
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :name                     "transactor",
                                                :env                      [{:name "TRANSACTOR_HOST", :value "transactor"}
                                                                           {:name "TRANSACTOR_ALT_HOST", :value "transactor"}
                                                                           {:name "TRANSACTOR_PORT", :value "4334"}],
                                                :ports                    [{:name "main", :containerPort 4334, :protocol "TCP"}
                                                                           {:name "h2", :containerPort 4335, :protocol "TCP"}
                                                                           {:name "other", :containerPort 4336, :protocol "TCP"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :imagePullPolicy          "IfNotPresent",
                                                :image                    "quay.io/nubank/nudev-transactor:7edadc4",
                                                :resources                {}}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-218-235.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}
   {:metadata {:labels            {:formicarium.io/application "zookeeper", :pod-template-hash "2898348612"},
               :ownerReferences   [{:apiVersion         "apps/v1",
                                    :kind               "ReplicaSet",
                                    :name               "zookeeper-6dfd78db56",
                                    :uid                "ec61264b-1830-11e9-a919-06375bf528b4",
                                    :controller         true,
                                    :blockOwnerDeletion true}],
               :creationTimestamp "2019-01-14T19:16:41Z",
               :uid               "ec61ce8c-1830-11e9-a919-06375bf528b4",
               :name              "zookeeper-6dfd78db56-9hlct",
               :resourceVersion   "16195953",
               :selfLink          "/api/v1/namespaces/carlos/pods/zookeeper-6dfd78db56-9hlct",
               :namespace         "carlos",
               :generateName      "zookeeper-6dfd78db56-"},
    :spec     {:serviceAccount                "default",
               :securityContext               {},
               :hostname                      "zookeeper",
               :containers                    [{:name                     "zookeeper",
                                                :image                    "quay.io/nubank/nudev-exhibitor:latest",
                                                :ports                    [{:name "client", :containerPort 2181, :protocol "TCP"}
                                                                           {:name "follower", :containerPort 2888, :protocol "TCP"}
                                                                           {:name "leader", :containerPort 3888, :protocol "TCP"}
                                                                           {:name "exhibitor", :containerPort 8080, :protocol "TCP"}],
                                                :resources                {},
                                                :volumeMounts             [{:name      "default-token-r8zrn",
                                                                            :readOnly  true,
                                                                            :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                                :terminationMessagePath   "/dev/termination-log",
                                                :terminationMessagePolicy "File",
                                                :imagePullPolicy          "Always"}],
               :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
               :schedulerName                 "default-scheduler",
               :priority                      0,
               :nodeName                      "ip-10-129-210-13.ec2.internal",
               :restartPolicy                 "Always",
               :dnsPolicy                     "ClusterFirst",
               :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}
                                               {:key               "node.kubernetes.io/unreachable",
                                                :operator          "Exists",
                                                :effect            "NoExecute",
                                                :tolerationSeconds 300}],
               :serviceAccountName            "default",
               :terminationGracePeriodSeconds 30}}])


(def hive
  {:metadata {:labels            {:formicarium.io/application "hive", :pod-template-hash "2857630519"},
              :ownerReferences   [{:apiVersion         "apps/v1",
                                   :kind               "ReplicaSet",
                                   :name               "hive-6d9cb7495f",
                                   :uid                "ec1b5c03-1830-11e9-a919-06375bf528b4",
                                   :controller         true,
                                   :blockOwnerDeletion true}],
              :creationTimestamp "2019-01-14T19:16:41Z",
              :uid               "ec1e0655-1830-11e9-a919-06375bf528b4",
              :name              "hive-6d9cb7495f-pvgjv",
              :resourceVersion   "16195908",
              :selfLink          "/api/v1/namespaces/carlos/pods/hive-6d9cb7495f-pvgjv",
              :namespace         "carlos",
              :generateName      "hive-6d9cb7495f-"},
   :spec     {:serviceAccount                "default",
              :securityContext               {},
              :hostname                      "hive",
              :containers                    [{:name                     "hive",
                                               :image                    "formicarium/hive:5d98c11ea5db32bd8db5478e7389f0ac668d79b3",
                                               :ports                    [{:name "default", :containerPort 8080, :protocol "TCP"}
                                                                          {:name "repl", :containerPort 2222, :protocol "TCP"}
                                                                          {:name "zmq", :containerPort 9898, :protocol "TCP"}],
                                               :resources                {},
                                               :volumeMounts             [{:name      "default-token-r8zrn",
                                                                           :readOnly  true,
                                                                           :mountPath "/var/run/secrets/kubernetes.io/serviceaccount"}],
                                               :terminationMessagePath   "/dev/termination-log",
                                               :terminationMessagePolicy "File",
                                               :imagePullPolicy          "IfNotPresent"}],
              :volumes                       [{:name "default-token-r8zrn", :secret {:secretName "default-token-r8zrn", :defaultMode 420}}],
              :schedulerName                 "default-scheduler",
              :priority                      0,
              :nodeName                      "ip-10-129-218-235.ec2.internal",
              :restartPolicy                 "Always",
              :dnsPolicy                     "ClusterFirst",
              :tolerations                   [{:key               "node.kubernetes.io/not-ready",
                                               :operator          "Exists",
                                               :effect            "NoExecute",
                                               :tolerationSeconds 300}
                                              {:key               "node.kubernetes.io/unreachable",
                                               :operator          "Exists",
                                               :effect            "NoExecute",
                                               :tolerationSeconds 300}],
              :serviceAccountName            "default",
              :terminationGracePeriodSeconds 30}})
