# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  test:
    docker:
    - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "project.clj" }}
        - v1-dependencies-
    - run: lein deps
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "project.clj" }}
    - run: lein midje

  check-version:
    docker:
    - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    steps:
    - run: check-version.sh

  build-and-push:
    machine: true
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: build-and-publish
        command: |
          docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
          build.sh


workflows:
  version: 2
  soil_workflow:
    jobs:
    - test
    - check-version
    - build-and-push:
        requires:
        - check-version
        - test
        filters:
          branches:
            only: master
