# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  test:
    docker:
    - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "project.clj" }}
        - v1-dependencies-
    - run: lein deps
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "project.clj" }}
    - run: lein midje

  check-version:
    docker:
    - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    steps:
    - checkout
    - run: ./check-version.sh

  build:
    working_directory: ~/repo
    docker:
    - image: circleci/clojure:lein-2.7.1
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - run:
        name: build
        command: ./build.sh
    - persist_to_workspace:
        root: ~/repo
        paths:
          - push.sh
          - resources/base.edn
          - target/soil-0.0.1-SNAPSHOT-standalone.jar

  publish:
    machine: true
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: build-and-publish
        command: |
          docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
          find .
          ./push.sh


workflows:
  version: 2
  soil_workflow:
    jobs:
    - test
    - check-version
    - build:
        requires:
        - check-version
        - test
        filters:
          branches:
            only: master
    - publish:
        requires:
        - build
        filters:
          branches:
            only: master
